/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletsRouteImport } from './routes/wallets'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as ReferralsRouteImport } from './routes/referrals'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as LaunchpadRouteImport } from './routes/launchpad'
import { Route as IntelRouteImport } from './routes/intel'
import { Route as InsidersRouteImport } from './routes/insiders'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as DiagRouteImport } from './routes/diag'
import { Route as BridgeRouteImport } from './routes/bridge'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as XHandleRouteImport } from './routes/x.$handle'
import { Route as UHandleRouteImport } from './routes/u.$handle'
import { Route as TokenCaRouteImport } from './routes/token.$ca'
import { Route as PadCaRouteImport } from './routes/pad.$ca'
import { Route as InsiderWalletRouteImport } from './routes/insider.$wallet'
import { Route as BotSplatRouteImport } from './routes/bot/$'
import { Route as ApiWarmRouteImport } from './routes/api/warm'
import { Route as ApiVersionRouteImport } from './routes/api/version'
import { Route as ApiTokensRouteImport } from './routes/api/tokens'
import { Route as ApiTokenpageRouteImport } from './routes/api/tokenpage'
import { Route as ApiSwaprouteRouteImport } from './routes/api/swaproute'
import { Route as ApiStocksRouteImport } from './routes/api/stocks'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiRpcRouteImport } from './routes/api/rpc'
import { Route as ApiRefCreditRouteImport } from './routes/api/ref-credit'
import { Route as ApiPadlistRouteImport } from './routes/api/padlist'
import { Route as ApiPadMetaRouteImport } from './routes/api/pad-meta'
import { Route as ApiHelpRouteImport } from './routes/api/help'
import { Route as ApiHealRouteImport } from './routes/api/heal'
import { Route as ApiPadLogoCaRouteImport } from './routes/api/pad-logo.$ca'
import { Route as ApiLogoIpfsCidRouteImport } from './routes/api/logo.ipfs.$cid'

const WalletsRoute = WalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchpadRoute = LaunchpadRouteImport.update({
  id: '/launchpad',
  path: '/launchpad',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelRoute = IntelRouteImport.update({
  id: '/intel',
  path: '/intel',
  getParentRoute: () => rootRouteImport,
} as any)
const InsidersRoute = InsidersRouteImport.update({
  id: '/insiders',
  path: '/insiders',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagRoute = DiagRouteImport.update({
  id: '/diag',
  path: '/diag',
  getParentRoute: () => rootRouteImport,
} as any)
const BridgeRoute = BridgeRouteImport.update({
  id: '/bridge',
  path: '/bridge',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const XHandleRoute = XHandleRouteImport.update({
  id: '/x/$handle',
  path: '/x/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const UHandleRoute = UHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenCaRoute = TokenCaRouteImport.update({
  id: '/token/$ca',
  path: '/token/$ca',
  getParentRoute: () => rootRouteImport,
} as any)
const PadCaRoute = PadCaRouteImport.update({
  id: '/pad/$ca',
  path: '/pad/$ca',
  getParentRoute: () => rootRouteImport,
} as any)
const InsiderWalletRoute = InsiderWalletRouteImport.update({
  id: '/insider/$wallet',
  path: '/insider/$wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const BotSplatRoute = BotSplatRouteImport.update({
  id: '/bot/$',
  path: '/bot/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWarmRoute = ApiWarmRouteImport.update({
  id: '/api/warm',
  path: '/api/warm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVersionRoute = ApiVersionRouteImport.update({
  id: '/api/version',
  path: '/api/version',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTokensRoute = ApiTokensRouteImport.update({
  id: '/api/tokens',
  path: '/api/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTokenpageRoute = ApiTokenpageRouteImport.update({
  id: '/api/tokenpage',
  path: '/api/tokenpage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSwaprouteRoute = ApiSwaprouteRouteImport.update({
  id: '/api/swaproute',
  path: '/api/swaproute',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStocksRoute = ApiStocksRouteImport.update({
  id: '/api/stocks',
  path: '/api/stocks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcRoute = ApiRpcRouteImport.update({
  id: '/api/rpc',
  path: '/api/rpc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRefCreditRoute = ApiRefCreditRouteImport.update({
  id: '/api/ref-credit',
  path: '/api/ref-credit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPadlistRoute = ApiPadlistRouteImport.update({
  id: '/api/padlist',
  path: '/api/padlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPadMetaRoute = ApiPadMetaRouteImport.update({
  id: '/api/pad-meta',
  path: '/api/pad-meta',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHelpRoute = ApiHelpRouteImport.update({
  id: '/api/help',
  path: '/api/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealRoute = ApiHealRouteImport.update({
  id: '/api/heal',
  path: '/api/heal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPadLogoCaRoute = ApiPadLogoCaRouteImport.update({
  id: '/api/pad-logo/$ca',
  path: '/api/pad-logo/$ca',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLogoIpfsCidRoute = ApiLogoIpfsCidRouteImport.update({
  id: '/api/logo/ipfs/$cid',
  path: '/api/logo/ipfs/$cid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/bridge': typeof BridgeRoute
  '/diag': typeof DiagRoute
  '/feed': typeof FeedRoute
  '/insiders': typeof InsidersRoute
  '/intel': typeof IntelRoute
  '/launchpad': typeof LaunchpadRoute
  '/leaderboard': typeof LeaderboardRoute
  '/portfolio': typeof PortfolioRoute
  '/profile': typeof ProfileRoute
  '/referrals': typeof ReferralsRoute
  '/rewards': typeof RewardsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/scan': typeof ScanRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trade': typeof TradeRoute
  '/wallets': typeof WalletsRoute
  '/api/heal': typeof ApiHealRoute
  '/api/help': typeof ApiHelpRoute
  '/api/pad-meta': typeof ApiPadMetaRoute
  '/api/padlist': typeof ApiPadlistRoute
  '/api/ref-credit': typeof ApiRefCreditRoute
  '/api/rpc': typeof ApiRpcRoute
  '/api/search': typeof ApiSearchRoute
  '/api/stocks': typeof ApiStocksRoute
  '/api/swaproute': typeof ApiSwaprouteRoute
  '/api/tokenpage': typeof ApiTokenpageRoute
  '/api/tokens': typeof ApiTokensRoute
  '/api/version': typeof ApiVersionRoute
  '/api/warm': typeof ApiWarmRoute
  '/bot/$': typeof BotSplatRoute
  '/insider/$wallet': typeof InsiderWalletRoute
  '/pad/$ca': typeof PadCaRoute
  '/token/$ca': typeof TokenCaRoute
  '/u/$handle': typeof UHandleRoute
  '/x/$handle': typeof XHandleRoute
  '/api/pad-logo/$ca': typeof ApiPadLogoCaRoute
  '/api/logo/ipfs/$cid': typeof ApiLogoIpfsCidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/bridge': typeof BridgeRoute
  '/diag': typeof DiagRoute
  '/feed': typeof FeedRoute
  '/insiders': typeof InsidersRoute
  '/intel': typeof IntelRoute
  '/launchpad': typeof LaunchpadRoute
  '/leaderboard': typeof LeaderboardRoute
  '/portfolio': typeof PortfolioRoute
  '/profile': typeof ProfileRoute
  '/referrals': typeof ReferralsRoute
  '/rewards': typeof RewardsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/scan': typeof ScanRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trade': typeof TradeRoute
  '/wallets': typeof WalletsRoute
  '/api/heal': typeof ApiHealRoute
  '/api/help': typeof ApiHelpRoute
  '/api/pad-meta': typeof ApiPadMetaRoute
  '/api/padlist': typeof ApiPadlistRoute
  '/api/ref-credit': typeof ApiRefCreditRoute
  '/api/rpc': typeof ApiRpcRoute
  '/api/search': typeof ApiSearchRoute
  '/api/stocks': typeof ApiStocksRoute
  '/api/swaproute': typeof ApiSwaprouteRoute
  '/api/tokenpage': typeof ApiTokenpageRoute
  '/api/tokens': typeof ApiTokensRoute
  '/api/version': typeof ApiVersionRoute
  '/api/warm': typeof ApiWarmRoute
  '/bot/$': typeof BotSplatRoute
  '/insider/$wallet': typeof InsiderWalletRoute
  '/pad/$ca': typeof PadCaRoute
  '/token/$ca': typeof TokenCaRoute
  '/u/$handle': typeof UHandleRoute
  '/x/$handle': typeof XHandleRoute
  '/api/pad-logo/$ca': typeof ApiPadLogoCaRoute
  '/api/logo/ipfs/$cid': typeof ApiLogoIpfsCidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/bridge': typeof BridgeRoute
  '/diag': typeof DiagRoute
  '/feed': typeof FeedRoute
  '/insiders': typeof InsidersRoute
  '/intel': typeof IntelRoute
  '/launchpad': typeof LaunchpadRoute
  '/leaderboard': typeof LeaderboardRoute
  '/portfolio': typeof PortfolioRoute
  '/profile': typeof ProfileRoute
  '/referrals': typeof ReferralsRoute
  '/rewards': typeof RewardsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/scan': typeof ScanRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trade': typeof TradeRoute
  '/wallets': typeof WalletsRoute
  '/api/heal': typeof ApiHealRoute
  '/api/help': typeof ApiHelpRoute
  '/api/pad-meta': typeof ApiPadMetaRoute
  '/api/padlist': typeof ApiPadlistRoute
  '/api/ref-credit': typeof ApiRefCreditRoute
  '/api/rpc': typeof ApiRpcRoute
  '/api/search': typeof ApiSearchRoute
  '/api/stocks': typeof ApiStocksRoute
  '/api/swaproute': typeof ApiSwaprouteRoute
  '/api/tokenpage': typeof ApiTokenpageRoute
  '/api/tokens': typeof ApiTokensRoute
  '/api/version': typeof ApiVersionRoute
  '/api/warm': typeof ApiWarmRoute
  '/bot/$': typeof BotSplatRoute
  '/insider/$wallet': typeof InsiderWalletRoute
  '/pad/$ca': typeof PadCaRoute
  '/token/$ca': typeof TokenCaRoute
  '/u/$handle': typeof UHandleRoute
  '/x/$handle': typeof XHandleRoute
  '/api/pad-logo/$ca': typeof ApiPadLogoCaRoute
  '/api/logo/ipfs/$cid': typeof ApiLogoIpfsCidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/bridge'
    | '/diag'
    | '/feed'
    | '/insiders'
    | '/intel'
    | '/launchpad'
    | '/leaderboard'
    | '/portfolio'
    | '/profile'
    | '/referrals'
    | '/rewards'
    | '/robots.txt'
    | '/scan'
    | '/sitemap.xml'
    | '/trade'
    | '/wallets'
    | '/api/heal'
    | '/api/help'
    | '/api/pad-meta'
    | '/api/padlist'
    | '/api/ref-credit'
    | '/api/rpc'
    | '/api/search'
    | '/api/stocks'
    | '/api/swaproute'
    | '/api/tokenpage'
    | '/api/tokens'
    | '/api/version'
    | '/api/warm'
    | '/bot/$'
    | '/insider/$wallet'
    | '/pad/$ca'
    | '/token/$ca'
    | '/u/$handle'
    | '/x/$handle'
    | '/api/pad-logo/$ca'
    | '/api/logo/ipfs/$cid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/bridge'
    | '/diag'
    | '/feed'
    | '/insiders'
    | '/intel'
    | '/launchpad'
    | '/leaderboard'
    | '/portfolio'
    | '/profile'
    | '/referrals'
    | '/rewards'
    | '/robots.txt'
    | '/scan'
    | '/sitemap.xml'
    | '/trade'
    | '/wallets'
    | '/api/heal'
    | '/api/help'
    | '/api/pad-meta'
    | '/api/padlist'
    | '/api/ref-credit'
    | '/api/rpc'
    | '/api/search'
    | '/api/stocks'
    | '/api/swaproute'
    | '/api/tokenpage'
    | '/api/tokens'
    | '/api/version'
    | '/api/warm'
    | '/bot/$'
    | '/insider/$wallet'
    | '/pad/$ca'
    | '/token/$ca'
    | '/u/$handle'
    | '/x/$handle'
    | '/api/pad-logo/$ca'
    | '/api/logo/ipfs/$cid'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/bridge'
    | '/diag'
    | '/feed'
    | '/insiders'
    | '/intel'
    | '/launchpad'
    | '/leaderboard'
    | '/portfolio'
    | '/profile'
    | '/referrals'
    | '/rewards'
    | '/robots.txt'
    | '/scan'
    | '/sitemap.xml'
    | '/trade'
    | '/wallets'
    | '/api/heal'
    | '/api/help'
    | '/api/pad-meta'
    | '/api/padlist'
    | '/api/ref-credit'
    | '/api/rpc'
    | '/api/search'
    | '/api/stocks'
    | '/api/swaproute'
    | '/api/tokenpage'
    | '/api/tokens'
    | '/api/version'
    | '/api/warm'
    | '/bot/$'
    | '/insider/$wallet'
    | '/pad/$ca'
    | '/token/$ca'
    | '/u/$handle'
    | '/x/$handle'
    | '/api/pad-logo/$ca'
    | '/api/logo/ipfs/$cid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  BridgeRoute: typeof BridgeRoute
  DiagRoute: typeof DiagRoute
  FeedRoute: typeof FeedRoute
  InsidersRoute: typeof InsidersRoute
  IntelRoute: typeof IntelRoute
  LaunchpadRoute: typeof LaunchpadRoute
  LeaderboardRoute: typeof LeaderboardRoute
  PortfolioRoute: typeof PortfolioRoute
  ProfileRoute: typeof ProfileRoute
  ReferralsRoute: typeof ReferralsRoute
  RewardsRoute: typeof RewardsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  ScanRoute: typeof ScanRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TradeRoute: typeof TradeRoute
  WalletsRoute: typeof WalletsRoute
  ApiHealRoute: typeof ApiHealRoute
  ApiHelpRoute: typeof ApiHelpRoute
  ApiPadMetaRoute: typeof ApiPadMetaRoute
  ApiPadlistRoute: typeof ApiPadlistRoute
  ApiRefCreditRoute: typeof ApiRefCreditRoute
  ApiRpcRoute: typeof ApiRpcRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiStocksRoute: typeof ApiStocksRoute
  ApiSwaprouteRoute: typeof ApiSwaprouteRoute
  ApiTokenpageRoute: typeof ApiTokenpageRoute
  ApiTokensRoute: typeof ApiTokensRoute
  ApiVersionRoute: typeof ApiVersionRoute
  ApiWarmRoute: typeof ApiWarmRoute
  BotSplatRoute: typeof BotSplatRoute
  InsiderWalletRoute: typeof InsiderWalletRoute
  PadCaRoute: typeof PadCaRoute
  TokenCaRoute: typeof TokenCaRoute
  UHandleRoute: typeof UHandleRoute
  XHandleRoute: typeof XHandleRoute
  ApiPadLogoCaRoute: typeof ApiPadLogoCaRoute
  ApiLogoIpfsCidRoute: typeof ApiLogoIpfsCidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallets': {
      id: '/wallets'
      path: '/wallets'
      fullPath: '/wallets'
      preLoaderRoute: typeof WalletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launchpad': {
      id: '/launchpad'
      path: '/launchpad'
      fullPath: '/launchpad'
      preLoaderRoute: typeof LaunchpadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intel': {
      id: '/intel'
      path: '/intel'
      fullPath: '/intel'
      preLoaderRoute: typeof IntelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insiders': {
      id: '/insiders'
      path: '/insiders'
      fullPath: '/insiders'
      preLoaderRoute: typeof InsidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diag': {
      id: '/diag'
      path: '/diag'
      fullPath: '/diag'
      preLoaderRoute: typeof DiagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bridge': {
      id: '/bridge'
      path: '/bridge'
      fullPath: '/bridge'
      preLoaderRoute: typeof BridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/x/$handle': {
      id: '/x/$handle'
      path: '/x/$handle'
      fullPath: '/x/$handle'
      preLoaderRoute: typeof XHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$handle': {
      id: '/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof UHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/token/$ca': {
      id: '/token/$ca'
      path: '/token/$ca'
      fullPath: '/token/$ca'
      preLoaderRoute: typeof TokenCaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pad/$ca': {
      id: '/pad/$ca'
      path: '/pad/$ca'
      fullPath: '/pad/$ca'
      preLoaderRoute: typeof PadCaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insider/$wallet': {
      id: '/insider/$wallet'
      path: '/insider/$wallet'
      fullPath: '/insider/$wallet'
      preLoaderRoute: typeof InsiderWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bot/$': {
      id: '/bot/$'
      path: '/bot/$'
      fullPath: '/bot/$'
      preLoaderRoute: typeof BotSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/warm': {
      id: '/api/warm'
      path: '/api/warm'
      fullPath: '/api/warm'
      preLoaderRoute: typeof ApiWarmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/version': {
      id: '/api/version'
      path: '/api/version'
      fullPath: '/api/version'
      preLoaderRoute: typeof ApiVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tokens': {
      id: '/api/tokens'
      path: '/api/tokens'
      fullPath: '/api/tokens'
      preLoaderRoute: typeof ApiTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tokenpage': {
      id: '/api/tokenpage'
      path: '/api/tokenpage'
      fullPath: '/api/tokenpage'
      preLoaderRoute: typeof ApiTokenpageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/swaproute': {
      id: '/api/swaproute'
      path: '/api/swaproute'
      fullPath: '/api/swaproute'
      preLoaderRoute: typeof ApiSwaprouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stocks': {
      id: '/api/stocks'
      path: '/api/stocks'
      fullPath: '/api/stocks'
      preLoaderRoute: typeof ApiStocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc': {
      id: '/api/rpc'
      path: '/api/rpc'
      fullPath: '/api/rpc'
      preLoaderRoute: typeof ApiRpcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ref-credit': {
      id: '/api/ref-credit'
      path: '/api/ref-credit'
      fullPath: '/api/ref-credit'
      preLoaderRoute: typeof ApiRefCreditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/padlist': {
      id: '/api/padlist'
      path: '/api/padlist'
      fullPath: '/api/padlist'
      preLoaderRoute: typeof ApiPadlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pad-meta': {
      id: '/api/pad-meta'
      path: '/api/pad-meta'
      fullPath: '/api/pad-meta'
      preLoaderRoute: typeof ApiPadMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/help': {
      id: '/api/help'
      path: '/api/help'
      fullPath: '/api/help'
      preLoaderRoute: typeof ApiHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/heal': {
      id: '/api/heal'
      path: '/api/heal'
      fullPath: '/api/heal'
      preLoaderRoute: typeof ApiHealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pad-logo/$ca': {
      id: '/api/pad-logo/$ca'
      path: '/api/pad-logo/$ca'
      fullPath: '/api/pad-logo/$ca'
      preLoaderRoute: typeof ApiPadLogoCaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/logo/ipfs/$cid': {
      id: '/api/logo/ipfs/$cid'
      path: '/api/logo/ipfs/$cid'
      fullPath: '/api/logo/ipfs/$cid'
      preLoaderRoute: typeof ApiLogoIpfsCidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  BridgeRoute: BridgeRoute,
  DiagRoute: DiagRoute,
  FeedRoute: FeedRoute,
  InsidersRoute: InsidersRoute,
  IntelRoute: IntelRoute,
  LaunchpadRoute: LaunchpadRoute,
  LeaderboardRoute: LeaderboardRoute,
  PortfolioRoute: PortfolioRoute,
  ProfileRoute: ProfileRoute,
  ReferralsRoute: ReferralsRoute,
  RewardsRoute: RewardsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ScanRoute: ScanRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TradeRoute: TradeRoute,
  WalletsRoute: WalletsRoute,
  ApiHealRoute: ApiHealRoute,
  ApiHelpRoute: ApiHelpRoute,
  ApiPadMetaRoute: ApiPadMetaRoute,
  ApiPadlistRoute: ApiPadlistRoute,
  ApiRefCreditRoute: ApiRefCreditRoute,
  ApiRpcRoute: ApiRpcRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiStocksRoute: ApiStocksRoute,
  ApiSwaprouteRoute: ApiSwaprouteRoute,
  ApiTokenpageRoute: ApiTokenpageRoute,
  ApiTokensRoute: ApiTokensRoute,
  ApiVersionRoute: ApiVersionRoute,
  ApiWarmRoute: ApiWarmRoute,
  BotSplatRoute: BotSplatRoute,
  InsiderWalletRoute: InsiderWalletRoute,
  PadCaRoute: PadCaRoute,
  TokenCaRoute: TokenCaRoute,
  UHandleRoute: UHandleRoute,
  XHandleRoute: XHandleRoute,
  ApiPadLogoCaRoute: ApiPadLogoCaRoute,
  ApiLogoIpfsCidRoute: ApiLogoIpfsCidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
