/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Wallets2RouteImport } from './routes/wallets2'
import { Route as WalletsRouteImport } from './routes/wallets'
import { Route as Trade2RouteImport } from './routes/trade2'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as Swap2RouteImport } from './routes/swap2'
import { Route as SwapRouteImport } from './routes/swap'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as Scan2RouteImport } from './routes/scan2'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as Rewards2RouteImport } from './routes/rewards2'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as Referrals2RouteImport } from './routes/referrals2'
import { Route as ReferralsRouteImport } from './routes/referrals'
import { Route as Profile2RouteImport } from './routes/profile2'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as Portfolio2RouteImport } from './routes/portfolio2'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as Pay2RouteImport } from './routes/pay2'
import { Route as PayRouteImport } from './routes/pay'
import { Route as Leaderboard2RouteImport } from './routes/leaderboard2'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as Launchpad2RouteImport } from './routes/launchpad2'
import { Route as LaunchpadRouteImport } from './routes/launchpad'
import { Route as Intel2RouteImport } from './routes/intel2'
import { Route as IntelRouteImport } from './routes/intel'
import { Route as Insiders2RouteImport } from './routes/insiders2'
import { Route as InsidersRouteImport } from './routes/insiders'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as DiagRouteImport } from './routes/diag'
import { Route as Bridge2RouteImport } from './routes/bridge2'
import { Route as BridgeRouteImport } from './routes/bridge'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as XHandleRouteImport } from './routes/x.$handle'
import { Route as UHandleRouteImport } from './routes/u.$handle'
import { Route as Token2CaRouteImport } from './routes/token2.$ca'
import { Route as TokenCaRouteImport } from './routes/token.$ca'
import { Route as PadCaRouteImport } from './routes/pad.$ca'
import { Route as InsiderWalletRouteImport } from './routes/insider.$wallet'
import { Route as BotSplatRouteImport } from './routes/bot/$'
import { Route as ApiWarmRouteImport } from './routes/api/warm'
import { Route as ApiVersionRouteImport } from './routes/api/version'
import { Route as ApiTokensRouteImport } from './routes/api/tokens'
import { Route as ApiTokenpageRouteImport } from './routes/api/tokenpage'
import { Route as ApiSwaprouteRouteImport } from './routes/api/swaproute'
import { Route as ApiSupplyRouteImport } from './routes/api/supply'
import { Route as ApiStocksRouteImport } from './routes/api/stocks'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiRpcRouteImport } from './routes/api/rpc'
import { Route as ApiRefCreditRouteImport } from './routes/api/ref-credit'
import { Route as ApiPadlistRouteImport } from './routes/api/padlist'
import { Route as ApiPadcountsRouteImport } from './routes/api/padcounts'
import { Route as ApiPadMetaRouteImport } from './routes/api/pad-meta'
import { Route as ApiHelpRouteImport } from './routes/api/help'
import { Route as ApiHealRouteImport } from './routes/api/heal'
import { Route as ApiPadLogoCaRouteImport } from './routes/api/pad-logo.$ca'
import { Route as ApiLogoIpfsCidRouteImport } from './routes/api/logo.ipfs.$cid'

const Wallets2Route = Wallets2RouteImport.update({
  id: '/wallets2',
  path: '/wallets2',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletsRoute = WalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => rootRouteImport,
} as any)
const Trade2Route = Trade2RouteImport.update({
  id: '/trade2',
  path: '/trade2',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const Swap2Route = Swap2RouteImport.update({
  id: '/swap2',
  path: '/swap2',
  getParentRoute: () => rootRouteImport,
} as any)
const SwapRoute = SwapRouteImport.update({
  id: '/swap',
  path: '/swap',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const Scan2Route = Scan2RouteImport.update({
  id: '/scan2',
  path: '/scan2',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const Rewards2Route = Rewards2RouteImport.update({
  id: '/rewards2',
  path: '/rewards2',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const Referrals2Route = Referrals2RouteImport.update({
  id: '/referrals2',
  path: '/referrals2',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const Profile2Route = Profile2RouteImport.update({
  id: '/profile2',
  path: '/profile2',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const Portfolio2Route = Portfolio2RouteImport.update({
  id: '/portfolio2',
  path: '/portfolio2',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const Pay2Route = Pay2RouteImport.update({
  id: '/pay2',
  path: '/pay2',
  getParentRoute: () => rootRouteImport,
} as any)
const PayRoute = PayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const Leaderboard2Route = Leaderboard2RouteImport.update({
  id: '/leaderboard2',
  path: '/leaderboard2',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const Launchpad2Route = Launchpad2RouteImport.update({
  id: '/launchpad2',
  path: '/launchpad2',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchpadRoute = LaunchpadRouteImport.update({
  id: '/launchpad',
  path: '/launchpad',
  getParentRoute: () => rootRouteImport,
} as any)
const Intel2Route = Intel2RouteImport.update({
  id: '/intel2',
  path: '/intel2',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelRoute = IntelRouteImport.update({
  id: '/intel',
  path: '/intel',
  getParentRoute: () => rootRouteImport,
} as any)
const Insiders2Route = Insiders2RouteImport.update({
  id: '/insiders2',
  path: '/insiders2',
  getParentRoute: () => rootRouteImport,
} as any)
const InsidersRoute = InsidersRouteImport.update({
  id: '/insiders',
  path: '/insiders',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagRoute = DiagRouteImport.update({
  id: '/diag',
  path: '/diag',
  getParentRoute: () => rootRouteImport,
} as any)
const Bridge2Route = Bridge2RouteImport.update({
  id: '/bridge2',
  path: '/bridge2',
  getParentRoute: () => rootRouteImport,
} as any)
const BridgeRoute = BridgeRouteImport.update({
  id: '/bridge',
  path: '/bridge',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const XHandleRoute = XHandleRouteImport.update({
  id: '/x/$handle',
  path: '/x/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const UHandleRoute = UHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const Token2CaRoute = Token2CaRouteImport.update({
  id: '/token2/$ca',
  path: '/token2/$ca',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenCaRoute = TokenCaRouteImport.update({
  id: '/token/$ca',
  path: '/token/$ca',
  getParentRoute: () => rootRouteImport,
} as any)
const PadCaRoute = PadCaRouteImport.update({
  id: '/pad/$ca',
  path: '/pad/$ca',
  getParentRoute: () => rootRouteImport,
} as any)
const InsiderWalletRoute = InsiderWalletRouteImport.update({
  id: '/insider/$wallet',
  path: '/insider/$wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const BotSplatRoute = BotSplatRouteImport.update({
  id: '/bot/$',
  path: '/bot/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWarmRoute = ApiWarmRouteImport.update({
  id: '/api/warm',
  path: '/api/warm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVersionRoute = ApiVersionRouteImport.update({
  id: '/api/version',
  path: '/api/version',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTokensRoute = ApiTokensRouteImport.update({
  id: '/api/tokens',
  path: '/api/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTokenpageRoute = ApiTokenpageRouteImport.update({
  id: '/api/tokenpage',
  path: '/api/tokenpage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSwaprouteRoute = ApiSwaprouteRouteImport.update({
  id: '/api/swaproute',
  path: '/api/swaproute',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSupplyRoute = ApiSupplyRouteImport.update({
  id: '/api/supply',
  path: '/api/supply',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStocksRoute = ApiStocksRouteImport.update({
  id: '/api/stocks',
  path: '/api/stocks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcRoute = ApiRpcRouteImport.update({
  id: '/api/rpc',
  path: '/api/rpc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRefCreditRoute = ApiRefCreditRouteImport.update({
  id: '/api/ref-credit',
  path: '/api/ref-credit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPadlistRoute = ApiPadlistRouteImport.update({
  id: '/api/padlist',
  path: '/api/padlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPadcountsRoute = ApiPadcountsRouteImport.update({
  id: '/api/padcounts',
  path: '/api/padcounts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPadMetaRoute = ApiPadMetaRouteImport.update({
  id: '/api/pad-meta',
  path: '/api/pad-meta',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHelpRoute = ApiHelpRouteImport.update({
  id: '/api/help',
  path: '/api/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealRoute = ApiHealRouteImport.update({
  id: '/api/heal',
  path: '/api/heal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPadLogoCaRoute = ApiPadLogoCaRouteImport.update({
  id: '/api/pad-logo/$ca',
  path: '/api/pad-logo/$ca',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLogoIpfsCidRoute = ApiLogoIpfsCidRouteImport.update({
  id: '/api/logo/ipfs/$cid',
  path: '/api/logo/ipfs/$cid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/bridge': typeof BridgeRoute
  '/bridge2': typeof Bridge2Route
  '/diag': typeof DiagRoute
  '/feed': typeof FeedRoute
  '/insiders': typeof InsidersRoute
  '/insiders2': typeof Insiders2Route
  '/intel': typeof IntelRoute
  '/intel2': typeof Intel2Route
  '/launchpad': typeof LaunchpadRoute
  '/launchpad2': typeof Launchpad2Route
  '/leaderboard': typeof LeaderboardRoute
  '/leaderboard2': typeof Leaderboard2Route
  '/pay': typeof PayRoute
  '/pay2': typeof Pay2Route
  '/portfolio': typeof PortfolioRoute
  '/portfolio2': typeof Portfolio2Route
  '/profile': typeof ProfileRoute
  '/profile2': typeof Profile2Route
  '/referrals': typeof ReferralsRoute
  '/referrals2': typeof Referrals2Route
  '/rewards': typeof RewardsRoute
  '/rewards2': typeof Rewards2Route
  '/robots.txt': typeof RobotsDottxtRoute
  '/scan': typeof ScanRoute
  '/scan2': typeof Scan2Route
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/swap': typeof SwapRoute
  '/swap2': typeof Swap2Route
  '/trade': typeof TradeRoute
  '/trade2': typeof Trade2Route
  '/wallets': typeof WalletsRoute
  '/wallets2': typeof Wallets2Route
  '/api/heal': typeof ApiHealRoute
  '/api/help': typeof ApiHelpRoute
  '/api/pad-meta': typeof ApiPadMetaRoute
  '/api/padcounts': typeof ApiPadcountsRoute
  '/api/padlist': typeof ApiPadlistRoute
  '/api/ref-credit': typeof ApiRefCreditRoute
  '/api/rpc': typeof ApiRpcRoute
  '/api/search': typeof ApiSearchRoute
  '/api/stocks': typeof ApiStocksRoute
  '/api/supply': typeof ApiSupplyRoute
  '/api/swaproute': typeof ApiSwaprouteRoute
  '/api/tokenpage': typeof ApiTokenpageRoute
  '/api/tokens': typeof ApiTokensRoute
  '/api/version': typeof ApiVersionRoute
  '/api/warm': typeof ApiWarmRoute
  '/bot/$': typeof BotSplatRoute
  '/insider/$wallet': typeof InsiderWalletRoute
  '/pad/$ca': typeof PadCaRoute
  '/token/$ca': typeof TokenCaRoute
  '/token2/$ca': typeof Token2CaRoute
  '/u/$handle': typeof UHandleRoute
  '/x/$handle': typeof XHandleRoute
  '/api/pad-logo/$ca': typeof ApiPadLogoCaRoute
  '/api/logo/ipfs/$cid': typeof ApiLogoIpfsCidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/bridge': typeof BridgeRoute
  '/bridge2': typeof Bridge2Route
  '/diag': typeof DiagRoute
  '/feed': typeof FeedRoute
  '/insiders': typeof InsidersRoute
  '/insiders2': typeof Insiders2Route
  '/intel': typeof IntelRoute
  '/intel2': typeof Intel2Route
  '/launchpad': typeof LaunchpadRoute
  '/launchpad2': typeof Launchpad2Route
  '/leaderboard': typeof LeaderboardRoute
  '/leaderboard2': typeof Leaderboard2Route
  '/pay': typeof PayRoute
  '/pay2': typeof Pay2Route
  '/portfolio': typeof PortfolioRoute
  '/portfolio2': typeof Portfolio2Route
  '/profile': typeof ProfileRoute
  '/profile2': typeof Profile2Route
  '/referrals': typeof ReferralsRoute
  '/referrals2': typeof Referrals2Route
  '/rewards': typeof RewardsRoute
  '/rewards2': typeof Rewards2Route
  '/robots.txt': typeof RobotsDottxtRoute
  '/scan': typeof ScanRoute
  '/scan2': typeof Scan2Route
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/swap': typeof SwapRoute
  '/swap2': typeof Swap2Route
  '/trade': typeof TradeRoute
  '/trade2': typeof Trade2Route
  '/wallets': typeof WalletsRoute
  '/wallets2': typeof Wallets2Route
  '/api/heal': typeof ApiHealRoute
  '/api/help': typeof ApiHelpRoute
  '/api/pad-meta': typeof ApiPadMetaRoute
  '/api/padcounts': typeof ApiPadcountsRoute
  '/api/padlist': typeof ApiPadlistRoute
  '/api/ref-credit': typeof ApiRefCreditRoute
  '/api/rpc': typeof ApiRpcRoute
  '/api/search': typeof ApiSearchRoute
  '/api/stocks': typeof ApiStocksRoute
  '/api/supply': typeof ApiSupplyRoute
  '/api/swaproute': typeof ApiSwaprouteRoute
  '/api/tokenpage': typeof ApiTokenpageRoute
  '/api/tokens': typeof ApiTokensRoute
  '/api/version': typeof ApiVersionRoute
  '/api/warm': typeof ApiWarmRoute
  '/bot/$': typeof BotSplatRoute
  '/insider/$wallet': typeof InsiderWalletRoute
  '/pad/$ca': typeof PadCaRoute
  '/token/$ca': typeof TokenCaRoute
  '/token2/$ca': typeof Token2CaRoute
  '/u/$handle': typeof UHandleRoute
  '/x/$handle': typeof XHandleRoute
  '/api/pad-logo/$ca': typeof ApiPadLogoCaRoute
  '/api/logo/ipfs/$cid': typeof ApiLogoIpfsCidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/bridge': typeof BridgeRoute
  '/bridge2': typeof Bridge2Route
  '/diag': typeof DiagRoute
  '/feed': typeof FeedRoute
  '/insiders': typeof InsidersRoute
  '/insiders2': typeof Insiders2Route
  '/intel': typeof IntelRoute
  '/intel2': typeof Intel2Route
  '/launchpad': typeof LaunchpadRoute
  '/launchpad2': typeof Launchpad2Route
  '/leaderboard': typeof LeaderboardRoute
  '/leaderboard2': typeof Leaderboard2Route
  '/pay': typeof PayRoute
  '/pay2': typeof Pay2Route
  '/portfolio': typeof PortfolioRoute
  '/portfolio2': typeof Portfolio2Route
  '/profile': typeof ProfileRoute
  '/profile2': typeof Profile2Route
  '/referrals': typeof ReferralsRoute
  '/referrals2': typeof Referrals2Route
  '/rewards': typeof RewardsRoute
  '/rewards2': typeof Rewards2Route
  '/robots.txt': typeof RobotsDottxtRoute
  '/scan': typeof ScanRoute
  '/scan2': typeof Scan2Route
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/swap': typeof SwapRoute
  '/swap2': typeof Swap2Route
  '/trade': typeof TradeRoute
  '/trade2': typeof Trade2Route
  '/wallets': typeof WalletsRoute
  '/wallets2': typeof Wallets2Route
  '/api/heal': typeof ApiHealRoute
  '/api/help': typeof ApiHelpRoute
  '/api/pad-meta': typeof ApiPadMetaRoute
  '/api/padcounts': typeof ApiPadcountsRoute
  '/api/padlist': typeof ApiPadlistRoute
  '/api/ref-credit': typeof ApiRefCreditRoute
  '/api/rpc': typeof ApiRpcRoute
  '/api/search': typeof ApiSearchRoute
  '/api/stocks': typeof ApiStocksRoute
  '/api/supply': typeof ApiSupplyRoute
  '/api/swaproute': typeof ApiSwaprouteRoute
  '/api/tokenpage': typeof ApiTokenpageRoute
  '/api/tokens': typeof ApiTokensRoute
  '/api/version': typeof ApiVersionRoute
  '/api/warm': typeof ApiWarmRoute
  '/bot/$': typeof BotSplatRoute
  '/insider/$wallet': typeof InsiderWalletRoute
  '/pad/$ca': typeof PadCaRoute
  '/token/$ca': typeof TokenCaRoute
  '/token2/$ca': typeof Token2CaRoute
  '/u/$handle': typeof UHandleRoute
  '/x/$handle': typeof XHandleRoute
  '/api/pad-logo/$ca': typeof ApiPadLogoCaRoute
  '/api/logo/ipfs/$cid': typeof ApiLogoIpfsCidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/bridge'
    | '/bridge2'
    | '/diag'
    | '/feed'
    | '/insiders'
    | '/insiders2'
    | '/intel'
    | '/intel2'
    | '/launchpad'
    | '/launchpad2'
    | '/leaderboard'
    | '/leaderboard2'
    | '/pay'
    | '/pay2'
    | '/portfolio'
    | '/portfolio2'
    | '/profile'
    | '/profile2'
    | '/referrals'
    | '/referrals2'
    | '/rewards'
    | '/rewards2'
    | '/robots.txt'
    | '/scan'
    | '/scan2'
    | '/sitemap.xml'
    | '/swap'
    | '/swap2'
    | '/trade'
    | '/trade2'
    | '/wallets'
    | '/wallets2'
    | '/api/heal'
    | '/api/help'
    | '/api/pad-meta'
    | '/api/padcounts'
    | '/api/padlist'
    | '/api/ref-credit'
    | '/api/rpc'
    | '/api/search'
    | '/api/stocks'
    | '/api/supply'
    | '/api/swaproute'
    | '/api/tokenpage'
    | '/api/tokens'
    | '/api/version'
    | '/api/warm'
    | '/bot/$'
    | '/insider/$wallet'
    | '/pad/$ca'
    | '/token/$ca'
    | '/token2/$ca'
    | '/u/$handle'
    | '/x/$handle'
    | '/api/pad-logo/$ca'
    | '/api/logo/ipfs/$cid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/bridge'
    | '/bridge2'
    | '/diag'
    | '/feed'
    | '/insiders'
    | '/insiders2'
    | '/intel'
    | '/intel2'
    | '/launchpad'
    | '/launchpad2'
    | '/leaderboard'
    | '/leaderboard2'
    | '/pay'
    | '/pay2'
    | '/portfolio'
    | '/portfolio2'
    | '/profile'
    | '/profile2'
    | '/referrals'
    | '/referrals2'
    | '/rewards'
    | '/rewards2'
    | '/robots.txt'
    | '/scan'
    | '/scan2'
    | '/sitemap.xml'
    | '/swap'
    | '/swap2'
    | '/trade'
    | '/trade2'
    | '/wallets'
    | '/wallets2'
    | '/api/heal'
    | '/api/help'
    | '/api/pad-meta'
    | '/api/padcounts'
    | '/api/padlist'
    | '/api/ref-credit'
    | '/api/rpc'
    | '/api/search'
    | '/api/stocks'
    | '/api/supply'
    | '/api/swaproute'
    | '/api/tokenpage'
    | '/api/tokens'
    | '/api/version'
    | '/api/warm'
    | '/bot/$'
    | '/insider/$wallet'
    | '/pad/$ca'
    | '/token/$ca'
    | '/token2/$ca'
    | '/u/$handle'
    | '/x/$handle'
    | '/api/pad-logo/$ca'
    | '/api/logo/ipfs/$cid'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/bridge'
    | '/bridge2'
    | '/diag'
    | '/feed'
    | '/insiders'
    | '/insiders2'
    | '/intel'
    | '/intel2'
    | '/launchpad'
    | '/launchpad2'
    | '/leaderboard'
    | '/leaderboard2'
    | '/pay'
    | '/pay2'
    | '/portfolio'
    | '/portfolio2'
    | '/profile'
    | '/profile2'
    | '/referrals'
    | '/referrals2'
    | '/rewards'
    | '/rewards2'
    | '/robots.txt'
    | '/scan'
    | '/scan2'
    | '/sitemap.xml'
    | '/swap'
    | '/swap2'
    | '/trade'
    | '/trade2'
    | '/wallets'
    | '/wallets2'
    | '/api/heal'
    | '/api/help'
    | '/api/pad-meta'
    | '/api/padcounts'
    | '/api/padlist'
    | '/api/ref-credit'
    | '/api/rpc'
    | '/api/search'
    | '/api/stocks'
    | '/api/supply'
    | '/api/swaproute'
    | '/api/tokenpage'
    | '/api/tokens'
    | '/api/version'
    | '/api/warm'
    | '/bot/$'
    | '/insider/$wallet'
    | '/pad/$ca'
    | '/token/$ca'
    | '/token2/$ca'
    | '/u/$handle'
    | '/x/$handle'
    | '/api/pad-logo/$ca'
    | '/api/logo/ipfs/$cid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  BridgeRoute: typeof BridgeRoute
  Bridge2Route: typeof Bridge2Route
  DiagRoute: typeof DiagRoute
  FeedRoute: typeof FeedRoute
  InsidersRoute: typeof InsidersRoute
  Insiders2Route: typeof Insiders2Route
  IntelRoute: typeof IntelRoute
  Intel2Route: typeof Intel2Route
  LaunchpadRoute: typeof LaunchpadRoute
  Launchpad2Route: typeof Launchpad2Route
  LeaderboardRoute: typeof LeaderboardRoute
  Leaderboard2Route: typeof Leaderboard2Route
  PayRoute: typeof PayRoute
  Pay2Route: typeof Pay2Route
  PortfolioRoute: typeof PortfolioRoute
  Portfolio2Route: typeof Portfolio2Route
  ProfileRoute: typeof ProfileRoute
  Profile2Route: typeof Profile2Route
  ReferralsRoute: typeof ReferralsRoute
  Referrals2Route: typeof Referrals2Route
  RewardsRoute: typeof RewardsRoute
  Rewards2Route: typeof Rewards2Route
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  ScanRoute: typeof ScanRoute
  Scan2Route: typeof Scan2Route
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SwapRoute: typeof SwapRoute
  Swap2Route: typeof Swap2Route
  TradeRoute: typeof TradeRoute
  Trade2Route: typeof Trade2Route
  WalletsRoute: typeof WalletsRoute
  Wallets2Route: typeof Wallets2Route
  ApiHealRoute: typeof ApiHealRoute
  ApiHelpRoute: typeof ApiHelpRoute
  ApiPadMetaRoute: typeof ApiPadMetaRoute
  ApiPadcountsRoute: typeof ApiPadcountsRoute
  ApiPadlistRoute: typeof ApiPadlistRoute
  ApiRefCreditRoute: typeof ApiRefCreditRoute
  ApiRpcRoute: typeof ApiRpcRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiStocksRoute: typeof ApiStocksRoute
  ApiSupplyRoute: typeof ApiSupplyRoute
  ApiSwaprouteRoute: typeof ApiSwaprouteRoute
  ApiTokenpageRoute: typeof ApiTokenpageRoute
  ApiTokensRoute: typeof ApiTokensRoute
  ApiVersionRoute: typeof ApiVersionRoute
  ApiWarmRoute: typeof ApiWarmRoute
  BotSplatRoute: typeof BotSplatRoute
  InsiderWalletRoute: typeof InsiderWalletRoute
  PadCaRoute: typeof PadCaRoute
  TokenCaRoute: typeof TokenCaRoute
  Token2CaRoute: typeof Token2CaRoute
  UHandleRoute: typeof UHandleRoute
  XHandleRoute: typeof XHandleRoute
  ApiPadLogoCaRoute: typeof ApiPadLogoCaRoute
  ApiLogoIpfsCidRoute: typeof ApiLogoIpfsCidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallets2': {
      id: '/wallets2'
      path: '/wallets2'
      fullPath: '/wallets2'
      preLoaderRoute: typeof Wallets2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallets': {
      id: '/wallets'
      path: '/wallets'
      fullPath: '/wallets'
      preLoaderRoute: typeof WalletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade2': {
      id: '/trade2'
      path: '/trade2'
      fullPath: '/trade2'
      preLoaderRoute: typeof Trade2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swap2': {
      id: '/swap2'
      path: '/swap2'
      fullPath: '/swap2'
      preLoaderRoute: typeof Swap2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swap': {
      id: '/swap'
      path: '/swap'
      fullPath: '/swap'
      preLoaderRoute: typeof SwapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan2': {
      id: '/scan2'
      path: '/scan2'
      fullPath: '/scan2'
      preLoaderRoute: typeof Scan2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards2': {
      id: '/rewards2'
      path: '/rewards2'
      fullPath: '/rewards2'
      preLoaderRoute: typeof Rewards2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals2': {
      id: '/referrals2'
      path: '/referrals2'
      fullPath: '/referrals2'
      preLoaderRoute: typeof Referrals2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile2': {
      id: '/profile2'
      path: '/profile2'
      fullPath: '/profile2'
      preLoaderRoute: typeof Profile2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio2': {
      id: '/portfolio2'
      path: '/portfolio2'
      fullPath: '/portfolio2'
      preLoaderRoute: typeof Portfolio2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay2': {
      id: '/pay2'
      path: '/pay2'
      fullPath: '/pay2'
      preLoaderRoute: typeof Pay2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard2': {
      id: '/leaderboard2'
      path: '/leaderboard2'
      fullPath: '/leaderboard2'
      preLoaderRoute: typeof Leaderboard2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launchpad2': {
      id: '/launchpad2'
      path: '/launchpad2'
      fullPath: '/launchpad2'
      preLoaderRoute: typeof Launchpad2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launchpad': {
      id: '/launchpad'
      path: '/launchpad'
      fullPath: '/launchpad'
      preLoaderRoute: typeof LaunchpadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intel2': {
      id: '/intel2'
      path: '/intel2'
      fullPath: '/intel2'
      preLoaderRoute: typeof Intel2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intel': {
      id: '/intel'
      path: '/intel'
      fullPath: '/intel'
      preLoaderRoute: typeof IntelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insiders2': {
      id: '/insiders2'
      path: '/insiders2'
      fullPath: '/insiders2'
      preLoaderRoute: typeof Insiders2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insiders': {
      id: '/insiders'
      path: '/insiders'
      fullPath: '/insiders'
      preLoaderRoute: typeof InsidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diag': {
      id: '/diag'
      path: '/diag'
      fullPath: '/diag'
      preLoaderRoute: typeof DiagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bridge2': {
      id: '/bridge2'
      path: '/bridge2'
      fullPath: '/bridge2'
      preLoaderRoute: typeof Bridge2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bridge': {
      id: '/bridge'
      path: '/bridge'
      fullPath: '/bridge'
      preLoaderRoute: typeof BridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/x/$handle': {
      id: '/x/$handle'
      path: '/x/$handle'
      fullPath: '/x/$handle'
      preLoaderRoute: typeof XHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$handle': {
      id: '/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof UHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/token2/$ca': {
      id: '/token2/$ca'
      path: '/token2/$ca'
      fullPath: '/token2/$ca'
      preLoaderRoute: typeof Token2CaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/token/$ca': {
      id: '/token/$ca'
      path: '/token/$ca'
      fullPath: '/token/$ca'
      preLoaderRoute: typeof TokenCaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pad/$ca': {
      id: '/pad/$ca'
      path: '/pad/$ca'
      fullPath: '/pad/$ca'
      preLoaderRoute: typeof PadCaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insider/$wallet': {
      id: '/insider/$wallet'
      path: '/insider/$wallet'
      fullPath: '/insider/$wallet'
      preLoaderRoute: typeof InsiderWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bot/$': {
      id: '/bot/$'
      path: '/bot/$'
      fullPath: '/bot/$'
      preLoaderRoute: typeof BotSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/warm': {
      id: '/api/warm'
      path: '/api/warm'
      fullPath: '/api/warm'
      preLoaderRoute: typeof ApiWarmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/version': {
      id: '/api/version'
      path: '/api/version'
      fullPath: '/api/version'
      preLoaderRoute: typeof ApiVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tokens': {
      id: '/api/tokens'
      path: '/api/tokens'
      fullPath: '/api/tokens'
      preLoaderRoute: typeof ApiTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tokenpage': {
      id: '/api/tokenpage'
      path: '/api/tokenpage'
      fullPath: '/api/tokenpage'
      preLoaderRoute: typeof ApiTokenpageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/swaproute': {
      id: '/api/swaproute'
      path: '/api/swaproute'
      fullPath: '/api/swaproute'
      preLoaderRoute: typeof ApiSwaprouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/supply': {
      id: '/api/supply'
      path: '/api/supply'
      fullPath: '/api/supply'
      preLoaderRoute: typeof ApiSupplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stocks': {
      id: '/api/stocks'
      path: '/api/stocks'
      fullPath: '/api/stocks'
      preLoaderRoute: typeof ApiStocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc': {
      id: '/api/rpc'
      path: '/api/rpc'
      fullPath: '/api/rpc'
      preLoaderRoute: typeof ApiRpcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ref-credit': {
      id: '/api/ref-credit'
      path: '/api/ref-credit'
      fullPath: '/api/ref-credit'
      preLoaderRoute: typeof ApiRefCreditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/padlist': {
      id: '/api/padlist'
      path: '/api/padlist'
      fullPath: '/api/padlist'
      preLoaderRoute: typeof ApiPadlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/padcounts': {
      id: '/api/padcounts'
      path: '/api/padcounts'
      fullPath: '/api/padcounts'
      preLoaderRoute: typeof ApiPadcountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pad-meta': {
      id: '/api/pad-meta'
      path: '/api/pad-meta'
      fullPath: '/api/pad-meta'
      preLoaderRoute: typeof ApiPadMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/help': {
      id: '/api/help'
      path: '/api/help'
      fullPath: '/api/help'
      preLoaderRoute: typeof ApiHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/heal': {
      id: '/api/heal'
      path: '/api/heal'
      fullPath: '/api/heal'
      preLoaderRoute: typeof ApiHealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pad-logo/$ca': {
      id: '/api/pad-logo/$ca'
      path: '/api/pad-logo/$ca'
      fullPath: '/api/pad-logo/$ca'
      preLoaderRoute: typeof ApiPadLogoCaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/logo/ipfs/$cid': {
      id: '/api/logo/ipfs/$cid'
      path: '/api/logo/ipfs/$cid'
      fullPath: '/api/logo/ipfs/$cid'
      preLoaderRoute: typeof ApiLogoIpfsCidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  BridgeRoute: BridgeRoute,
  Bridge2Route: Bridge2Route,
  DiagRoute: DiagRoute,
  FeedRoute: FeedRoute,
  InsidersRoute: InsidersRoute,
  Insiders2Route: Insiders2Route,
  IntelRoute: IntelRoute,
  Intel2Route: Intel2Route,
  LaunchpadRoute: LaunchpadRoute,
  Launchpad2Route: Launchpad2Route,
  LeaderboardRoute: LeaderboardRoute,
  Leaderboard2Route: Leaderboard2Route,
  PayRoute: PayRoute,
  Pay2Route: Pay2Route,
  PortfolioRoute: PortfolioRoute,
  Portfolio2Route: Portfolio2Route,
  ProfileRoute: ProfileRoute,
  Profile2Route: Profile2Route,
  ReferralsRoute: ReferralsRoute,
  Referrals2Route: Referrals2Route,
  RewardsRoute: RewardsRoute,
  Rewards2Route: Rewards2Route,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ScanRoute: ScanRoute,
  Scan2Route: Scan2Route,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SwapRoute: SwapRoute,
  Swap2Route: Swap2Route,
  TradeRoute: TradeRoute,
  Trade2Route: Trade2Route,
  WalletsRoute: WalletsRoute,
  Wallets2Route: Wallets2Route,
  ApiHealRoute: ApiHealRoute,
  ApiHelpRoute: ApiHelpRoute,
  ApiPadMetaRoute: ApiPadMetaRoute,
  ApiPadcountsRoute: ApiPadcountsRoute,
  ApiPadlistRoute: ApiPadlistRoute,
  ApiRefCreditRoute: ApiRefCreditRoute,
  ApiRpcRoute: ApiRpcRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiStocksRoute: ApiStocksRoute,
  ApiSupplyRoute: ApiSupplyRoute,
  ApiSwaprouteRoute: ApiSwaprouteRoute,
  ApiTokenpageRoute: ApiTokenpageRoute,
  ApiTokensRoute: ApiTokensRoute,
  ApiVersionRoute: ApiVersionRoute,
  ApiWarmRoute: ApiWarmRoute,
  BotSplatRoute: BotSplatRoute,
  InsiderWalletRoute: InsiderWalletRoute,
  PadCaRoute: PadCaRoute,
  TokenCaRoute: TokenCaRoute,
  Token2CaRoute: Token2CaRoute,
  UHandleRoute: UHandleRoute,
  XHandleRoute: XHandleRoute,
  ApiPadLogoCaRoute: ApiPadLogoCaRoute,
  ApiLogoIpfsCidRoute: ApiLogoIpfsCidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
